Fixed: style guide consideration

diff --git a/dasp b/dasp
--- a/dasp
+++ b/dasp
@@ -1,10 +1,10 @@
 #!/bin/bash
+#
 # Data Spider (DASP) - perfom getting data for defined period from any data source
-# Usage description: see fx_usage()
+#
 # Style guide: https://google.github.io/styleguide/shell.xml
 
-function fx_usage()
-{
+function fx_usage() {
 
   echo "Usage: dasp [options]... [date_start] [date_end] (optional)
   
@@ -14,11 +14,11 @@ function fx_usage()
     -w (--awk-date-format)  - date format, used in current source data
     -k (--awk-date-field)   - field in source data, contains date-time, in awk terms
     -m (--months-format)    - months format, recognized by \$(date) command
-    -M (--months-custom)    - custom months, delimeted by ',' and content 11 delimetres
+    -M (--months-custom)    - custom months, delimeted by eleven ','
     -o (--date-offset)      - increase day +- while search files
     -n (--newermt)          - file from which modified date taken (optional)
     -b (--output-debug)     - debug data destination (optional)
-    -t (--tmp-file)         - use custom temp file for awk (optional)
+    -t (--tmp-file)         - use temp file for awk work instead of var (optional)
 
   Date flags:
     - set in any format recognized by \$(date) command
@@ -27,44 +27,41 @@ function fx_usage()
     1) alias dasp_apache_access='dasp -s ~/logs ' -f '*access*log' -o 1 -k 4 -w '[D/M/Y:h:m:s' -m '%b'
     2) dasp_apache_access \"yesterday 14:00\" now
     3) dasp_apache_access -n control_file
-  
-  Example for debug:
-    1) dasp 2>/dev/null | echo \"\$(head;tail)\"   # show 5 start and 5 end results
     " \
   | sed 's/^\s\s//' 1>&2
   
   exit 1
+
 }
 
-function sys_error()
-{
-  [[ $@ ]] && echo "error: $@" >&2
+function sys_error() {
+  [[ "$@" ]] && echo "error: $@" >&2
   critical_error_flag="1"
 }
 
-function sys_debug()
-{
+function sys_debug() {
   [[ "${DEBUG}" == 'true' ]] && echo -e "debug: $@" >&2
 }
 
-function sys_is_abort()
-{
-  [[ $critical_error_flag == '1' ]] && echo "exit" && exit 1
+function sys_is_abort() {
+  if [[ "${critical_error_flag}" == 1 ]]; then
+    echo "tip: type ./dasp -h for usage"
+    echo "exit"
+    exit 1
+  fi
 }
 
 # Set default values before iterating throught options
 
-function fx_define_vars()
-{
+function fx_define_vars() {
 
   critical_error_flag=''
-
-  TMP_FILE="$HOME/.dasp~"
-
   DEBUG='false'
 
+  TMP_FILE=''
+
   DATE_START=''
-  DATE_END="now"
+  DATE_END='now'
   
   DATE_OFFSET=''
 
@@ -81,25 +78,22 @@ function fx_define_vars()
   
 }
 
-# Set main options in 2 steps
-
-function fx_set_user_options()
-{
+function fx_getopts() {
 
   local OPTIND \
         flag
 
-  # Step 1: Iterate throught arguments for getting main options
+  # Get main options
 
-  while getopts "bhw:k:f:s:n:m:M:o:t:" flag
+  while getopts 'bhw:k:f:s:n:m:M:o:t:' flag
   do
     case "${flag}" in
     
       b) DEBUG='true' ;;
       t)
          TMP_FILE="${OPTARG}"
-         [[ -d $TMP_FILE ]] && sys_error 'Option -t - should be not path'
-         truncate --size 0 ${TMP_FILE} >&2 || sys_error 'Option -t - can`t create file'
+         [[ -d "${TMP_FILE}" ]] && sys_error 'Option -t - should be not path'
+         truncate --size 0 "${TMP_FILE}" >&2 || sys_error 'Option -t - can`t create file'
          ;;
 
       w) SRC_DATE_FORMAT="${OPTARG}" ;;
@@ -107,24 +101,24 @@ function fx_set_user_options()
       f) SRC_DATA_FNAME="${OPTARG}" ;;
 
       s)
-         SRC_DATA_PATH=$OPTARG
-         [[ ! -d $SRC_DATA_PATH ]] && sys_error 'Option -s - path is not exists' 
+         SRC_DATA_PATH="${OPTARG}"
+         [[ ! -d "${SRC_DATA_PATH}" ]] && sys_error 'Option -s - path is not exists' 
          ;;
       
       n)
-         NEWER_MT=$OPTARG
-         [[ ! -f $NEWER_MT ]] && sys_error 'Option -n - file not found'
-         DATE_START=`date -d @$(stat -c %Y $NEWER_MT) +%Y-%m-%dT%H:%M:%S`;;
+         NEWER_MT="${OPTARG}"
+         [[ ! -f "${NEWER_MT}" ]] && sys_error 'Option -n - file not found'
+         DATE_START=`date -d @$(stat -c %Y "${NEWER_MT}") +%Y-%m-%dT%H:%M:%S`;;
       
       m)
-         MONTHS_FORMAT=$OPTARG
-         if   [[ $MONTHS_FORMAT == "%m" ]]; then MONTHS_CUSTOM="01,02,03,04,05,
+         MONTHS_FORMAT="${OPTARG}"
+         if   [[ "$MONTHS_FORMAT" == "%m" ]]; then MONTHS_CUSTOM="01,02,03,04,05,
                                                                 06,07,08,09,10,
                                                                 11,12";
-         elif [[ $MONTHS_FORMAT == "%b" ]]; then MONTHS_CUSTOM="Jan,Feb,Mar,Apr,
+         elif [[ "$MONTHS_FORMAT" == "%b" ]]; then MONTHS_CUSTOM="Jan,Feb,Mar,Apr,
                                                                 May,Jun,Jul,Aug,
                                                                 Sep,Oct,Nov,Dec";
-         elif [[ $MONTHS_FORMAT == "%B" ]]; then MONTHS_CUSTOM="January,Febrary,
+         elif [[ "$MONTHS_FORMAT" == "%B" ]]; then MONTHS_CUSTOM="January,Febrary,
                                                                 Marth,April,May,
                                                                 June,Jule,August,
                                                                 September,October,
@@ -133,15 +127,15 @@ function fx_set_user_options()
          ;; 
 
       M)
-         MONTHS_CUSTOM=$OPTARG
-         if [[ $(echo $MONTHS_CUSTOM | grep -o "," | wc -l) != 11 ]]; then
+         MONTHS_CUSTOM="${OPTARG}"
+         if [[ $(echo "${MONTHS_CUSTOM}" | grep -o "," | wc -l) != 11 ]]; then
            sys_error 'Option -M - count of custom months must be 12 over ","'
          fi
          ;;
 
       o)
-         DATE_OFFSET=$OPTARG
-         [[ ! $DATE_OFFSET =~ ^[-+]?[0-9]+$ ]] && sys_error 'Option -o - isn`t digit' ;;
+         DATE_OFFSET="${OPTARG}"
+         [[ ! "${DATE_OFFSET}" =~ ^[-+]?[0-9]+$ ]] && sys_error 'Option -o - isn`t digit' ;;
 
       h) fx_usage ;;
       ?) sys_error ;;
@@ -149,19 +143,18 @@ function fx_set_user_options()
     esac
   done
   
-  sys_debug "script parametrs: $*";
+  sys_debug "script parametrs: $@";
 
-  # Step 2: Iterate throught arguments for getting dates
+  # Get dates
 
   shift "$((OPTIND-1))"
 
-  [[ ! -z $1 ]] && DATE_START=$1
-  [[ ! -z $2 ]] && DATE_END=$2
+  [[ -n "$1" ]] && DATE_START="$1"
+  [[ -n "$2" ]] && DATE_END="$2"
 
 }
 
-function fx_define_const()
-{
+function fx_define_const() {
   readonly TMP_FILE
   
   readonly DEBUG
@@ -183,45 +176,46 @@ function fx_define_const()
   readonly MONTHS_CUSTOM
 }
 
-function fx_check_required_options()
-{
+function fx_check_required_options() {
   
   # Check other required options
 
-  [[ -z $SRC_DATE_FORMAT ]] && sys_error 'Option -w is required'
-  [[ -z $SRC_DATE_FIELD ]] && sys_error 'Option -k is required'
-  [[ -z $SRC_DATA_FNAME ]] && sys_error 'Option -f is required'
-  [[ -z $SRC_DATA_PATH ]] && sys_error 'Option -s is required'
-  [[ -z $MONTHS_CUSTOM ]] && sys_error 'Option -M or -m is required'
+  [[ -z "${SRC_DATE_FORMAT}" ]] && sys_error 'Option -w is required'
+  [[ -z "${SRC_DATE_FIELD}" ]] && sys_error 'Option -k is required'
+  [[ -z "${SRC_DATA_FNAME}" ]] && sys_error 'Option -f is required'
+  [[ -z "${SRC_DATA_PATH}" ]] && sys_error 'Option -s is required'
+  [[ -z "${MONTHS_CUSTOM}" ]] && sys_error 'Option -M or -m is required'
   
   # Check required dates options
 
-  [[ -z $DATE_OFFSET ]] && sys_error 'Option -o is required'
-  [[ ! -z $DATE_START \
-    && ! -z $NEWER_MT ]] && sys_error 'Option -n and \$2 mutual voided'
-  [[ -z $DATE_START && -z $NEWER_MT ]] && sys_error '$1 as date_start is required'
-  [[ -z $DATE_END ]] && sys_error '$2 as date_end is required'
+  [[ -z "${DATE_OFFSET}" ]] && sys_error 'Option -o is required'
+  [[ -n "${DATE_START}" \
+    && -n "${NEWER_MT}" ]] && sys_error 'Option -n and \$2 mutual voided'
+  [[ -z "${DATE_START}" && -z "${NEWER_MT}" ]] && sys_error '\$1 as date_start is required'
+  [[ -z "${DATE_END}" ]] && sys_error '\$2 as date_end is required'
 
   # Clear tmp file and check avialabilities to write
 
-  sys_debug "Use ${TMP_FILE} temp file"
-  truncate --size 0 ${TMP_FILE} >&2 || sys_error 'Option -t - can`t create file'
+  if [[ ! -z "${TMP_FILE}" ]]; then
+    sys_debug "Use ${TMP_FILE} temp file"
+    truncate --size 0 "${TMP_FILE}" >&2 || sys_error 'Option -t - can`t create file'
+  else
+    sys_debug "Work without temp file"
+  fi
   
 }
 
-function fx_check_dates_format()
-{
+function fx_check_dates_format() {
 
   date -d "$DATE_START" > /dev/null 2>&1
-  [[ $(echo $?) != 0 ]] && sys_error 'Start date format is not recognized'
+  [[ $(echo "$?") != 0 ]] && sys_error 'Start date format is not recognized'
     
   date -d "$DATE_END" > /dev/null 2>&1
-  [[ $(echo $?) != 0 ]] && sys_error 'End date format is not recognized'
+  [[ $(echo "$?") != 0 ]] && sys_error 'End date format is not recognized'
 
 }
 
-function fx_find_files()
-{
+function fx_find_files() {
 
   local find_start \
         find_end \
@@ -231,41 +225,41 @@ function fx_find_files()
 
   # Prepare dates for find command
   
-  find_start=`date -d "$(date -d "$DATE_START" +%F) -${DATE_OFFSET}days" +%Y-%m-%d`
-  find_end=`date -d "$(date -d "$DATE_END" +%F) +${DATE_OFFSET}days" +%Y-%m-%d`
+  find_start=`date -d "$(date -d "${DATE_START}" +%F) -${DATE_OFFSET}days" +%Y-%m-%d`
+  find_end=`date -d "$(date -d "${DATE_END}" +%F) +${DATE_OFFSET}days" +%Y-%m-%d`
   
   # Find files between two dates and sort results by modification date
 
-  res_find=`find $SRC_DATA_PATH \
+  res_find=`find ${SRC_DATA_PATH} \
     -type f \
-    -name "$SRC_DATA_FNAME" \
-    -newermt "$find_start 00:00:00" ! -newermt "$find_end 23:59:59" \
+    -name "${SRC_DATA_FNAME}" \
+    -newermt "${find_start} 00:00:00" ! -newermt "${find_end} 23:59:59" \
     -exec ls -1rt "{}" +;`
 
   res_test=`find $SRC_DATA_PATH \
     -type f \
-    -name "$SRC_DATA_FNAME" \
-    -newermt "$find_start 00:00:00" ! -newermt "$find_end 23:59:59" \
+    -name "${SRC_DATA_FNAME}" \
+    -newermt "${find_start} 00:00:00" ! -newermt "${find_end} 23:59:59" \
     -exec cat {} \; | wc -l`
   
   # Save data to debug channel
   
   err_code="$?"
 
-  if [[ "$err_code" -ne 0 ]]; then
-    sys_error "Find command exits with code $err_code"
+  if [[ "${err_code}" -ne 0 ]]; then
+    sys_error "Find command exits with code ${err_code}"
   else
-    sys_debug "records in find: $res_test";
-    echo "$res_find"
+    sys_debug "records in find: ${res_test}";
+    echo "${res_find}"
   fi
 
 }
 
 
-function fx_filter_data()
-{ 
+function fx_filter_data() { 
 
   local i \
+        content \
         current_file \
         files_list \
         awk_start \
@@ -280,8 +274,8 @@ function fx_filter_data()
 
   # Prepare dates for awk command 
 
-  awk_start=`date -d "$DATE_START" "+%Y%m%d%H%M%S"`
-  awk_end=`date -d "$DATE_END" "+%Y%m%d%H%M%S"`
+  awk_start=`date -d "${DATE_START}" "+%Y%m%d%H%M%S"`
+  awk_end=`date -d "${DATE_END}" "+%Y%m%d%H%M%S"`
 
   # Iterate throught files_list 
   
@@ -292,24 +286,45 @@ function fx_filter_data()
   
     sys_debug "reading ${i} ${current_file}"
 
-    awk \
-      -v DATE_START="$awk_start" \
-      -v DATE_END="$awk_end" \
-      -v DATE_FORMAT="$SRC_DATE_FORMAT" \
-      -v DATE_FIELD="$SRC_DATE_FIELD" \
-      -v MONTHS_CUSTOM="$MONTHS_CUSTOM" \
-      -v DEBUG="$DEBUG" \
+    if [[ -n "${TMP_FILE}" ]]; then
+      awk \
+      -v DATE_START="${awk_start}" \
+      -v DATE_END="${awk_end}" \
+      -v DATE_FORMAT="${SRC_DATE_FORMAT}" \
+      -v DATE_FIELD="${SRC_DATE_FIELD}" \
+      -v MONTHS_CUSTOM="${MONTHS_CUSTOM}" \
+      -v DEBUG="${DEBUG}" \
       -F " " \
-      "$(awk_func)" $current_file >> $TMP_FILE
+      "$(awk_func)" ${current_file} >> ${TMP_FILE}
+    
+    else
+    
+      content=`awk \
+      -v DATE_START="${awk_start}" \
+      -v DATE_END="${awk_end}" \
+      -v DATE_FORMAT="${SRC_DATE_FORMAT}" \
+      -v DATE_FIELD="${SRC_DATE_FIELD}" \
+      -v MONTHS_CUSTOM="${MONTHS_CUSTOM}" \
+      -v DEBUG="${DEBUG}" \
+      -F " " \
+      "$(awk_func)" ${current_file}`
+
+      [[ -n "${content}" ]] && echo "${content}" && content=''
+
+    fi
 
     let i++
 
-  done <<< "$files_list"
+  done <<< "${files_list}"
+
+  # Show output
+
+  [[ -n "${TMP_FILE}" ]] && cat "${TMP_FILE}"
 
 }
 
-function awk_func
-{
+function awk_func {
+
   echo '
   BEGIN {
     # Form custom months array like ....
@@ -367,10 +382,10 @@ function awk_func
         print $0;
     }            
   } '
+
 }
 
-function main()
-{
+function main() {
 
   local files_list \
         records \
@@ -383,7 +398,7 @@ function main()
   # Define necessary options, vars and constants
 
   fx_define_vars
-  fx_set_user_options "$@"
+  fx_getopts "$@"
   fx_define_const
 
   fx_check_required_options
@@ -400,12 +415,7 @@ function main()
 
   # Filter records in files with dates range
 
-  fx_filter_data "$files_list"
-  sys_is_abort
-
-  # Show file
-
-  #$(cat $TMP_FILE) 
+  fx_filter_data "${files_list}"
 
 }
 
